sudo: false

language: python

python:
  - '3.6'

script:
  - python setup.py test

install:
  - python setup.py install

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: madedotcom
        password:
          secure: Wy/fHpwqy3dJmRGPZ835/J9ybKV4xWcWG6dCgqAiRZt6IwDZL2/pz8jaIudqTwUxiZlWKKQ9m0l40bPzw+q1yx2s/dpPHtTcMqXo73kwafNLGSSR7NWhiAJfNAIGQAY1Hr6Av1BGVCw4P8zBsnZGC41gNjzQ5uUGN6S/mjcrsoxwQuioqSdVOjxmGLEV+qKrsohjQ1k0IHj4gMKqY2pUmsqRq24jHayWmeV7paiccgpaMagrTD/v3aaUFISTjhpXNvxFuJeWtNnfXOcj5JKDBT4lmnHctjLeC1itR4ohob8HBvXYDgkPOXbcpwe6BmS84/fLCNUCkMJWBq8y3t6U8ZexzH4ReukVeLPGtCjUuKknh97IgoWWxdY2ZYUnjmQ7Kxz1ycTbyK3RO4h497tCc+5+6a2MistLnt9uRWphEbDGzaa65Nyuv2kj/ERD3qjcC/AiWY8qxOlSMfPwH8EpTaIX8WzbBVK0PDi4qHvOl8OmOi6OI3Nenr+htWa35l8hlLV4YofZ1yGtFmnqLBVlI7fzHYuRG060VqNYd8Sobg4lj0ho/6Mci2PtiBaEQGWoHfpnEgTjYg9t0xd/EJrxXuI34I55eI1CXCfYq1rMj+dA9Ldj0nrW77wZU6SQ2JnVzGubKbrQnAO2tAMUHLnxpetE1ZfwuFCpyurBuQzjw/Q=
        distributions: sdist bdist_wheel
