sudo: false

language: python

python:
  - '3.6'

script:
  - python setup.py test

install:
  - python setup.py install

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: madedotcom
        password:
          secure: p1YDHPzklGcsfmFFEq5xzXcCZxQynvc8aEpp0aFqqx3P015Us003w1jr2xLBiL32OUTgkIfZ/VksaoP5eWnJJwleXaNjmQBbRpFPOUVwBgyeEc2D5nJdiXrPan65iXtERRgUbi4ItbgoOOOsBa8gPwcjcqrtMJDlQcqoOkwKsgfZBVNH4/RimwM2HtPHeQaZUZhN8NuufOA5DAP4Wwp8lOOAj4qPDcY92hrm4hpHbZbbwxre33RDjneyGFHh2HcoyiXm92JKTCrsvU1AmO7wNKOKhPujA8Fi1G39qMKpKlLVs/6poZpsogwAPNwTB4Plc2A3QVfIwDZ8hZvdjpe7To8PMKCtIHhKpQHRoyp4A0zSbxfwWYw65MOTJWEz150VJ/otaaPilxAJSK2duJBlz5COc+wUP7QTmucL7zbWUcqmXUOaWi2VyOHfWXp6ZegcxLDkhIsICPu3G8okNu1ce2GejHyn2C+RZdyZYyGesc/DCj+n+jbBPJxnB0qo/H2Pq7cq7Xp+oxH36bBtNrIlMnAaw4yG7sEduh3gUNHKB0AL41NefUpEI4zjDhx3RhxGZnIT1pVHxK5wgQfF+mZGRDHB7KO1d5JeHG6gHdKAnDkpa7ynelEW2ne5lCWFUzewaM/U5gvrU0LQDwscELfSCT0o/lETM8BSEzFQLGf7kqs=
        distributions: sdist bdist_wheel
