sudo: false

language: python

python:
  - '3.6'

script:
  - python setup.py test

install:
  - python setup.py install

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: madedotcom
        password:
          secure: vfSINl6KW5GFAB9oA3Rpy/SE64trRV+xBLMQ29Kck5vtBrnNvTZ/ZXegbKooI8fb7kpXNJYQ0grmU5FVEA4lNnnviEj+8HhmH3E6NZP4RZPPkuvtyGLeBzWDtw3wX6lb7BVQ5i6P23merGjEaBNr0SEe4ifQgA9M4HaWzQOgwk3w0ZKT9LJxU10HIrCby1zoZPDw+x+Wb8KZrM0AKxWwfMuaSDPzvTOFQY3pfAflDCDNIYrJcJIBjb2rtQoiExAWctqG4JguFGx0oF86oUR+QKH7F/yCBDpzc64rZuEyo30Jykb4kfrcdDlmmy7i1gmjYIshe0iHxmXZppd0uZf8rp7qJ+XN5AuajP/GG/6GExDIhkPmGNpReWznjuu7m/FTWF4XEQtBmykAUjZRaSTm3KB6Ef3dKJJvU5p4dks/R3wSlv6S7QTUw1WzSZOsN2H+83TXPA/vW2kM20cN95PxTFLcCiX91ms6iojH2AqsEVuZ2XgC44qO4Qv5PGTEFbQ9Y/Ue8LiBiMUcgUMh7SfdNwtJmSOeZLHLwb69AGq260NYyli35/nN6G2+mDnuGyWypZfCuEfOkaBudx8yyzJAb4XVAMM3MIzhj/gvpmnCXTlUCdSshv64FAuwnqu3hWZ738eauzaFAJTQfWKB96jlkxSXKoQfMYiCHOZFghgNkjk=
        distributions: sdist bdist_wheel
