sudo: false
language: python
stages:
- name: test
- name: deploy
  if: tag IS present
python:
- '3.6'
jobs:
  include:
  - stage: test
    install:
    - python setup.py install
    script:
    - python setup.py test
  - stage: deploy
    python: 3.6
    script: skip
    deploy:
      provider: pypi
      user: madedotcom
      password:
        secure: OXOj4lqFXIukV1IioxccYMx58KGQ/+rT+gmda2rpeaL0yYOLe4M/w0HNBFmHXdT3Pqee53sWMqq+Mvw7mxfKoAGrokpcd//Qaz05G9eBDQCRPe5mNYF1b5DtnyK5uX+LjlttK6qlqaJlbyRr0xSpnSzC/5LAtjqdl+7fRsz6a4K6qImYk5Vbq7tQrJpTgzfB1lyzk/Wa0va2HcUvV2fOecfXf86kd+B0awFPWmdbpKpZEk69KdwgRF51t0BaAQqTlVgsJi05HwPT7hWulxRh7Ad7uEfwDsnAOV6F0zOGXJovUVZPT17/4m1cj9+BuRW2kLeI/+Y+i14Drkg/Jmf/jveM4v7yms3o580w/QMT2Q+0J/OY4uaa4KIluRd+JYw8U+s8j7W/LGvvXiANnJ1TNSpSzWLJlQk2+GZH5y25/67hX/atw2r7SLLd+iY++YwEMAb2ICwTSC0OWh2rEFuh4LKw8GjyzICpfqOYw8Iw91Dd4eHchnZcHXxA2EWvtQKHcuWQFyN1xkZ0s98NOF+yAmwu7FKnadpu1eSo+wMm10/uFMIwA0BbTnom94fD8jELIp8SHgsjfV+63nY6m21Oiinl90wgSdI3zWGBNji/Lg1gPBqK1qlmEqx957LiG39giKRK/ruZOym9GMpiFRlzxsAPrbMvugTm+FT/oGbwd0Q=
      distributions: sdist bdist_wheel
      on:
        tags: true
        all_branches: true
